name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]>
    # <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron: "27 14 * * 1"
  workflow_dispatch:

jobs:
  test-repo-gen:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: extractions/setup-just@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install cookiecutter
    - name: Generate Repo
      run: |
        cookiecutter . --no-input
    - name: Test Generated Repo Install
      run: |
        cd python-boilerplate
        git init
        git config --global user.email "doesnt.matter@email.com"
        git config --global user.name "Sally Tests"
        git add -A
        git commit -m "Initial commit"
        just install
    - name: Test Generated Repo Build
      run: |
        cd python-boilerplate
        just build
    - name: Test Generated Repo Docs
      run: |
        cd python-boilerplate
        just serve-docs
    - name: Test Generated Repo Clean
      run: |
        cd python-boilerplate
        just clean
    - name: Test Generated Repo Updates
      run: |
        cd python-boilerplate
        just update-from-cookiecutter
        git status